# Create full conda environment for development, including some useful tools
name: devel
channels:
  - conda-forge
dependencies:
  - python=3
  - numpy
  - requests
  - protobuf
  - netcdf4
  - jupyter
  - sphinx
  - sphinx-gallery
  - doc8
  - pytest
  - pytest-cov
  - pytest-flake8
  - pytest-runner
  - vcrpy
  - flake8
  - flake8-builtins
  - flake8-comprehensions
  - flake8-copyright
  - flake8-docstrings
  - flake8-import-order
  - flake8-mutable
  - flake8-pep3101
  - flake8-print
  - flake8-quotes
  - pep8-naming
  - matplotlib
  - xarray
  - cartopy
  - beautifulsoup4
